const {onCall,HttpsError}=require('firebase-functions/v2/https');
const {setGlobalOptions}=require('firebase-functions/v2');
const {initializeApp}=require('firebase-admin/app');
const {getFirestore,FieldValue}=require('firebase-admin/firestore');
const {getStorage}=require('firebase-admin/storage');
const bcrypt=require('bcryptjs');
const cheerio=require('cheerio');
const dns=require('node:dns').promises;
const net=require('node:net');
const crypto=require('node:crypto');

initializeApp();
setGlobalOptions({region:'us-central1',maxInstances:10});
const db=getFirestore();
const bucket=getStorage().bucket();

function ownerUid(){return process.env.OWNER_UID||''}
function requireOwner(req){if(!req.auth)throw new HttpsError('unauthenticated','Sign in first.');const owner=ownerUid();if(!owner||owner==='YOUR_OWNER_UID')throw new HttpsError('failed-precondition','OWNER_UID is not configured in functions/.env.');if(req.auth.uid!==owner)throw new HttpsError('permission-denied','Owner account only.');return req.auth.uid}
function cleanString(v,max=200){return String(v||'').trim().slice(0,max)}
function privateIp(ip){if(net.isIP(ip)===4){const p=ip.split('.').map(Number);return p[0]===10||p[0]===127||p[0]===0||p[0]>=224||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||(p[0]===100&&p[1]>=64&&p[1]<=127)}if(net.isIP(ip)===6){const s=ip.toLowerCase();return s==='::1'||s==='::'||s.startsWith('fc')||s.startsWith('fd')||s.startsWith('fe8')||s.startsWith('fe9')||s.startsWith('fea')||s.startsWith('feb')}return true}
async function validatePublicUrl(raw){let u;try{u=new URL(raw)}catch{throw new HttpsError('invalid-argument','Invalid URL.')}if(!['http:','https:'].includes(u.protocol))throw new HttpsError('invalid-argument','Only HTTP(S) URLs are allowed.');const host=u.hostname.toLowerCase();if(host==='localhost'||host.endsWith('.local'))throw new HttpsError('permission-denied','Local network URLs are not allowed.');const records=await dns.lookup(host,{all:true});if(!records.length||records.some(r=>privateIp(r.address)))throw new HttpsError('permission-denied','Private or reserved network addresses are not allowed.');return u}
async function safeFetch(raw,{maxBytes=2*1024*1024,accept='text/html,application/xhtml+xml'}={}){let u=await validatePublicUrl(raw);for(let i=0;i<5;i++){
  const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),12000);
  let res;try{res=await fetch(u,{redirect:'manual',signal:ctrl.signal,headers:{'user-agent':'Mozilla/5.0 NoxVaultMetadata/1.0','accept':accept}})}catch(e){clearTimeout(timer);throw new HttpsError('unavailable',`Remote request failed: ${e.message}`)}clearTimeout(timer);
  if([301,302,303,307,308].includes(res.status)){const loc=res.headers.get('location');if(!loc)throw new HttpsError('unavailable','Redirect had no location.');u=await validatePublicUrl(new URL(loc,u).toString());continue}
  if(!res.ok)throw new HttpsError('unavailable',`Remote server returned ${res.status}.`);
  const len=Number(res.headers.get('content-length')||0);if(len&&len>maxBytes)throw new HttpsError('resource-exhausted','Remote file is too large.');const buf=Buffer.from(await res.arrayBuffer());if(buf.length>maxBytes)throw new HttpsError('resource-exhausted','Remote file is too large.');return {res,buf,url:u.toString()};
}throw new HttpsError('unavailable','Too many redirects.')}
function meta($,selector,attr='content'){return cleanString($(selector).first().attr(attr)||'',1000)}
function text($,selector){return cleanString($(selector).first().text()||'',1000)}
function cleanTitle(title,host){let t=cleanString(title,240);const domain=host.replace(/^www\./,'').split('.')[0];const parts=t.split(/\s+[|–—-]\s+/);if(parts.length>1&&parts.at(-1).toLowerCase().includes(domain.toLowerCase()))parts.pop();return parts.join(' – ').trim()||host}
function flattenLd(v,out=[]){if(!v)return out;if(Array.isArray(v))v.forEach(x=>flattenLd(x,out));else if(typeof v==='object'){out.push(v);if(v['@graph'])flattenLd(v['@graph'],out)}return out}
function suggestions(textBlob){const s=textBlob.toLowerCase();const tags=[];const cats=new Set();const rules=[
  ['Solo',['solo','single performer']],['Masturbation',['masturbation','masturbating','jerk off','handjob self']],['Oral',['oral','blowjob','fellatio','cunnilingus']],['Hardcore',['hardcore']],['Soft',['softcore','soft porn','sensual']],['Anal',['anal']],['Amateur',['amateur','homemade']],['Professional',['studio','professional']],['Couples',['couple','couples']]
];for(const [cat,words] of rules)if(words.some(w=>s.includes(w)))cats.add(cat);for(const token of s.split(/[^a-z0-9]+/).filter(x=>x.length>=3&&x.length<=24)){if(['video','watch','porn','xxx','www','http','https','com','the','and','for','with','from'].includes(token))continue;if(!tags.includes(token))tags.push(token);if(tags.length>=12)break}return {tags,suggestedCategories:[...cats]}}

exports.createVault=onCall(async req=>{const uid=requireOwner(req);const name=cleanString(req.data?.name,60),password=cleanString(req.data?.password,256),description=cleanString(req.data?.description,140),color=cleanString(req.data?.color,20)||'#3377ff';if(name.length<1||password.length<4)throw new HttpsError('invalid-argument','Vault name and a password of at least 4 characters are required.');const ref=db.collection('users').doc(uid).collection('vaults').doc();const secret=db.collection('vaultSecrets').doc(`${uid}_${ref.id}`);const hash=await bcrypt.hash(password,12);await db.runTransaction(async tx=>{tx.set(ref,{id:ref.id,name,description,color,createdAt:FieldValue.serverTimestamp(),lastOpenedAt:null});tx.set(secret,{uid,vaultId:ref.id,passwordHash:hash,updatedAt:FieldValue.serverTimestamp()})});return {vaultId:ref.id}});
exports.verifyVaultPassword=onCall(async req=>{const uid=requireOwner(req),vaultId=cleanString(req.data?.vaultId,120),password=cleanString(req.data?.password,256);const s=await db.collection('vaultSecrets').doc(`${uid}_${vaultId}`).get();if(!s.exists)return {ok:false};return {ok:await bcrypt.compare(password,s.data().passwordHash)}});
exports.setVaultPassword=onCall(async req=>{const uid=requireOwner(req),vaultId=cleanString(req.data?.vaultId,120),password=cleanString(req.data?.password,256);if(password.length<4)throw new HttpsError('invalid-argument','Password must be at least 4 characters.');const v=await db.collection('users').doc(uid).collection('vaults').doc(vaultId).get();if(!v.exists)throw new HttpsError('not-found','Vault not found.');const hash=await bcrypt.hash(password,12);await db.collection('vaultSecrets').doc(`${uid}_${vaultId}`).set({uid,vaultId,passwordHash:hash,updatedAt:FieldValue.serverTimestamp()},{merge:true});return {ok:true}});
exports.deleteVault=onCall(async req=>{const uid=requireOwner(req),vaultId=cleanString(req.data?.vaultId,120);const ref=db.collection('users').doc(uid).collection('vaults').doc(vaultId);await db.recursiveDelete(ref);await db.collection('vaultSecrets').doc(`${uid}_${vaultId}`).delete().catch(()=>{});await bucket.deleteFiles({prefix:`users/${uid}/vaults/${vaultId}/`}).catch(()=>{});return {ok:true}});

exports.fetchPageMetadata=onCall(async req=>{requireOwner(req);const raw=cleanString(req.data?.url,3000);const {res,buf,url}=await safeFetch(raw,{maxBytes:3*1024*1024});const type=(res.headers.get('content-type')||'').toLowerCase();if(!type.includes('html')){const u=new URL(url);return {title:u.pathname.split('/').filter(Boolean).pop()||u.hostname,source:u.hostname.replace(/^www\./,''),thumbnail:'',embedUrl:'',mediaUrl:type.startsWith('video/')?url:'',tags:[],suggestedCategories:[]}}
  const html=buf.toString('utf8'),$=cheerio.load(html),u=new URL(url);let title=meta($,'meta[property="og:title"]')||meta($,'meta[name="twitter:title"]')||text($,'title')||u.hostname;let description=meta($,'meta[property="og:description"]')||meta($,'meta[name="description"]');let thumbnail=meta($,'meta[property="og:image"]')||meta($,'meta[name="twitter:image"]');let mediaUrl=meta($,'meta[property="og:video"]')||meta($,'meta[property="og:video:url"]');let embedUrl=meta($,'meta[property="og:video:secure_url"]');let keywords=meta($,'meta[name="keywords"]');let duration='';
  for(const el of $('script[type="application/ld+json"]').toArray()){try{const json=JSON.parse($(el).text());for(const obj of flattenLd(json)){title=title||obj.name||obj.headline;description=description||obj.description||'';thumbnail=thumbnail||(Array.isArray(obj.thumbnailUrl)?obj.thumbnailUrl[0]:obj.thumbnailUrl)||obj.image?.url||obj.image||'';embedUrl=embedUrl||obj.embedUrl||'';mediaUrl=mediaUrl||obj.contentUrl||'';duration=duration||obj.duration||'';if(obj.keywords)keywords+=` ${Array.isArray(obj.keywords)?obj.keywords.join(' '):obj.keywords}`}}catch{}}
  title=cleanTitle(title,u.hostname);const sug=suggestions(`${title} ${description} ${keywords}`);const absolutize=x=>{if(!x)return '';try{return new URL(x,u).toString()}catch{return ''}};return {title,description:cleanString(description,1000),source:u.hostname.replace(/^www\./,''),thumbnail:absolutize(thumbnail),embedUrl:absolutize(embedUrl),mediaUrl:absolutize(mediaUrl),duration:cleanString(duration,80),tags:sug.tags,suggestedCategories:sug.suggestedCategories,url};
});

exports.importRemoteImage=onCall(async req=>{const uid=requireOwner(req),vaultId=cleanString(req.data?.vaultId,120),raw=cleanString(req.data?.url,3000);const vault=await db.collection('users').doc(uid).collection('vaults').doc(vaultId).get();if(!vault.exists)throw new HttpsError('not-found','Vault not found.');const {res,buf,url}=await safeFetch(raw,{maxBytes:15*1024*1024,accept:'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8'});const type=(res.headers.get('content-type')||'').split(';')[0].trim().toLowerCase();if(!type.startsWith('image/'))throw new HttpsError('invalid-argument','The remote URL did not return an image.');const ext=({ 'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif','image/avif':'avif','image/svg+xml':'svg' })[type]||'img';const id=crypto.randomUUID(),path=`users/${uid}/vaults/${vaultId}/images/${id}.${ext}`,token=crypto.randomUUID();const file=bucket.file(path);await file.save(buf,{resumable:false,metadata:{contentType:type,metadata:{firebaseStorageDownloadTokens:token}}});const downloadUrl=`https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/${encodeURIComponent(path)}?alt=media&token=${token}`;const image={id,name:new URL(url).pathname.split('/').pop()||`image.${ext}`,url:downloadUrl,storagePath:path,sourceUrl:url,caption:'',tags:[],createdAt:FieldValue.serverTimestamp()};await db.collection('users').doc(uid).collection('vaults').doc(vaultId).collection('images').doc(id).set(image);return {image:{...image,createdAt:new Date().toISOString()}}});
